"""
Generate a court-ready forensic PDF report from the audit log.
"""
import io
from datetime import datetime, timezone
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

PAGE_W, PAGE_H = A4
MARGIN = 2.0 * cm

# ── Colour palette ──────────────────────────────────────────────────────────
C_DARK   = colors.HexColor("#0d1117")
C_BLUE   = colors.HexColor("#1f6feb")
C_LIGHT  = colors.HexColor("#c9d1d9")
C_GREY   = colors.HexColor("#30363d")
C_RED    = colors.HexColor("#f85149")
C_GREEN  = colors.HexColor("#3fb950")
C_WHITE  = colors.white
C_BLACK  = colors.black


def _styles():
    base = getSampleStyleSheet()

    title = ParagraphStyle(
        "ReportTitle",
        parent=base["Title"],
        fontSize=22,
        leading=28,
        textColor=C_DARK,
        alignment=TA_CENTER,
        spaceAfter=6,
    )
    subtitle = ParagraphStyle(
        "Subtitle",
        parent=base["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#57606a"),
        alignment=TA_CENTER,
        spaceAfter=4,
    )
    heading = ParagraphStyle(
        "SectionHeading",
        parent=base["Heading2"],
        fontSize=13,
        textColor=C_BLUE,
        spaceBefore=14,
        spaceAfter=4,
        borderPad=2,
    )
    body = ParagraphStyle(
        "Body",
        parent=base["Normal"],
        fontSize=9,
        leading=14,
        textColor=C_DARK,
    )
    mono = ParagraphStyle(
        "Mono",
        parent=base["Normal"],
        fontName="Courier",
        fontSize=7.5,
        leading=11,
        textColor=colors.HexColor("#24292f"),
    )
    small = ParagraphStyle(
        "Small",
        parent=base["Normal"],
        fontSize=7.5,
        leading=11,
        textColor=colors.HexColor("#57606a"),
    )
    disclaimer = ParagraphStyle(
        "Disclaimer",
        parent=base["Normal"],
        fontSize=8,
        leading=12,
        textColor=colors.HexColor("#57606a"),
        borderColor=colors.HexColor("#d0d7de"),
        borderWidth=1,
        borderPad=6,
        borderRadius=4,
    )
    return {
        "title": title,
        "subtitle": subtitle,
        "heading": heading,
        "body": body,
        "mono": mono,
        "small": small,
        "disclaimer": disclaimer,
    }


def _hr():
    return HRFlowable(width="100%", thickness=1, color=colors.HexColor("#d0d7de"), spaceAfter=8)


def _kv_table(rows: list[tuple[str, str]], s) -> Table:
    data = [[Paragraph(f"<b>{k}</b>", s["body"]), Paragraph(v, s["mono"])] for k, v in rows]
    t = Table(data, colWidths=[(PAGE_W - 2 * MARGIN) * 0.35, (PAGE_W - 2 * MARGIN) * 0.65])
    t.setStyle(
        TableStyle([
            ("VALIGN",    (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING",(0, 0), (-1, -1), 3),
            ("BOTTOMPADDING",(0,0),(-1,-1), 3),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#f6f8fa"), C_WHITE]),
        ])
    )
    return t


def generate_pdf(
    session_meta: dict,
    audit_entries: list[dict],
    case_number: str = "",
    analyst_name: str = "",
) -> bytes:
    """
    Build the forensic PDF report and return it as bytes.

    Parameters
    ----------
    session_meta   : the session's meta dict (from Session.meta)
    audit_entries  : list of operation dicts from AuditLogger.get_all()
    case_number    : optional case / file reference number
    analyst_name   : optional analyst name (printed on report)
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
    )

    s = _styles()
    story = []

    # ── Cover ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1.5 * cm))
    story.append(Paragraph("FORENSIC POINT CLOUD", s["title"]))
    story.append(Paragraph("ANALYSIS &amp; CLEANING REPORT", s["title"]))
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph("Generated by ForensicCloud v1.0", s["subtitle"]))
    story.append(Spacer(1, 0.2 * cm))

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    story.append(Paragraph(f"Report generated: {generated_at}", s["subtitle"]))
    story.append(Spacer(1, 1.0 * cm))
    story.append(_hr())

    # ── Case information ─────────────────────────────────────────────────────
    story.append(Paragraph("Case Information", s["heading"]))
    case_rows = [
        ("Case / File Reference", case_number or "— not provided —"),
        ("Analyst",               analyst_name or "— not provided —"),
        ("Session ID",            session_meta.get("session_id", "")),
        ("Analysis Date",         session_meta.get("created_at", "")[:19].replace("T", " ") + " UTC"),
    ]
    story.append(_kv_table(case_rows, s))
    story.append(Spacer(1, 0.5 * cm))

    # ── File information ─────────────────────────────────────────────────────
    story.append(Paragraph("Original File Information", s["heading"]))
    size_mb = session_meta.get("original_file_size_bytes", 0) / 1_048_576
    file_rows = [
        ("Original Filename",    session_meta.get("original_filename", "")),
        ("File Size",            f"{size_mb:.2f} MB ({session_meta.get('original_file_size_bytes', 0):,} bytes)"),
        ("SHA-256 Hash",         session_meta.get("original_file_hash", "")),
        ("Number of Scans",      str(session_meta.get("scan_count", 0))),
        ("Original Point Count", f"{session_meta.get('original_point_count', 0):,}"),
    ]
    story.append(_kv_table(file_rows, s))
    story.append(Spacer(1, 0.5 * cm))

    # ── Summary statistics ───────────────────────────────────────────────────
    orig_count   = session_meta.get("original_point_count", 0)
    curr_count   = session_meta.get("current_point_count", orig_count)
    total_removed = orig_count - curr_count
    pct_removed   = (total_removed / orig_count * 100) if orig_count > 0 else 0.0

    story.append(Paragraph("Summary Statistics", s["heading"]))
    summary_rows = [
        ("Original Point Count",       f"{orig_count:,}"),
        ("Final Point Count",          f"{curr_count:,}"),
        ("Total Points Removed",       f"{total_removed:,}  ({pct_removed:.2f}%)"),
        ("Cleaning Operations Applied", str(len(audit_entries))),
    ]
    story.append(_kv_table(summary_rows, s))
    story.append(Spacer(1, 0.8 * cm))

    # ── Operation log ────────────────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("Detailed Operation Log", s["heading"]))
    story.append(Paragraph(
        "The following table documents every cleaning operation applied to the point cloud "
        "in chronological order. Each entry records the algorithm, its parameters, the "
        "number of points removed, and the 3-D bounding box enclosing all removed points.",
        s["body"],
    ))
    story.append(Spacer(1, 0.4 * cm))

    if not audit_entries:
        story.append(Paragraph("No operations have been performed in this session.", s["small"]))
    else:
        for idx, entry in enumerate(audit_entries, start=1):
            story.append(Spacer(1, 0.3 * cm))
            story.append(Paragraph(
                f"Operation {idx} — {entry['algorithm']}",
                ParagraphStyle(
                    "OpHeading",
                    parent=s["body"],
                    fontSize=10,
                    textColor=C_BLUE,
                    fontName="Helvetica-Bold",
                    spaceBefore=6,
                ),
            ))

            bbox = entry.get("removed_bbox", {})
            mn = bbox.get("min", [0, 0, 0])
            mx = bbox.get("max", [0, 0, 0])
            bbox_str = (
                f"X: [{mn[0]:.4f}, {mx[0]:.4f}]  "
                f"Y: [{mn[1]:.4f}, {mx[1]:.4f}]  "
                f"Z: [{mn[2]:.4f}, {mx[2]:.4f}]"
            )

            region = entry.get("region_bbox")
            region_str = "Entire point cloud"
            if region:
                rmn, rmx = region.get("min", [0, 0, 0]), region.get("max", [0, 0, 0])
                region_str = (
                    f"X: [{rmn[0]:.4f}, {rmx[0]:.4f}]  "
                    f"Y: [{rmn[1]:.4f}, {rmx[1]:.4f}]  "
                    f"Z: [{rmn[2]:.4f}, {rmx[2]:.4f}]"
                )

            params_str = "  |  ".join(f"{k}={v}" for k, v in entry.get("params", {}).items())

            op_rows = [
                ("Timestamp (UTC)",         entry.get("timestamp", "")[:19].replace("T", " ")),
                ("Operation Type",          entry.get("operation_type", "")),
                ("Algorithm",               entry.get("algorithm", "")),
                ("Parameters",              params_str or "—"),
                ("Points Before",           f"{entry.get('points_before', 0):,}"),
                ("Points Removed",          f"{entry.get('points_removed', 0):,}"),
                ("Points After",            f"{entry.get('points_after', 0):,}"),
                ("Spatial Extent Removed",  bbox_str),
                ("Applied Region",          region_str),
                ("Operator Notes",          entry.get("operator_notes") or "—"),
            ]
            story.append(_kv_table(op_rows, s))

        story.append(Spacer(1, 0.8 * cm))

    # ── Chain-of-custody statement ───────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("Chain of Custody Statement", s["heading"]))
    story.append(_hr())

    coc_text = (
        "The original E57 point cloud file was ingested unmodified by the ForensicCloud "
        "platform. Its SHA-256 cryptographic hash was computed immediately upon receipt and "
        "is recorded in this report. All subsequent modifications were performed exclusively "
        "through the operations documented in the 'Detailed Operation Log' above. "
        "No data were altered, reordered, or overwritten outside of those logged operations. "
        "The platform retains the original file and its hash in its session store for "
        "independent verification.<br/><br/>"
        "This report was automatically generated by ForensicCloud and should be accompanied "
        "by the exported cleaned E57 file and the session database file when submitted as "
        "forensic evidence. The SHA-256 hash of the exported file should be recomputed by "
        "the receiving laboratory to confirm file integrity in transit."
    )
    story.append(Paragraph(coc_text, s["body"]))
    story.append(Spacer(1, 1.0 * cm))

    story.append(Paragraph("Disclaimer", s["heading"]))
    disclaimer_text = (
        "This report was produced by automated software. The accuracy of the cleaning "
        "operations is subject to the correctness of the parameters specified by the "
        "analyst. The analyst bears sole responsibility for verifying that removed points "
        "are not forensically significant. ForensicCloud's authors accept no liability for "
        "decisions made on the basis of this output."
    )
    story.append(Paragraph(disclaimer_text, s["disclaimer"]))
    story.append(Spacer(1, 1.5 * cm))

    # Signature blocks
    sig_data = [
        [Paragraph("<b>Analyst Signature</b>", s["body"]),
         Paragraph("<b>Reviewer Signature</b>", s["body"])],
        [Paragraph("_" * 40, s["mono"]), Paragraph("_" * 40, s["mono"])],
        [Paragraph(analyst_name or "Print name:", s["small"]),
         Paragraph("Print name:", s["small"])],
        [Paragraph("Date: __________________", s["small"]),
         Paragraph("Date: __________________", s["small"])],
    ]
    sig_table = Table(sig_data, colWidths=[(PAGE_W - 2 * MARGIN) / 2] * 2)
    sig_table.setStyle(TableStyle([
        ("VALIGN",       (0, 0), (-1, -1), "BOTTOM"),
        ("TOPPADDING",   (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
    ]))
    story.append(sig_table)

    doc.build(story)
    buf.seek(0)
    return buf.read()
